In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
# Membaca dataset
df = pd.read_csv('iris.csv')

# Memeriksa informasi data
print(df.info())

# Memeriksa nilai null
df.isnull().sum()

# Fill missing values with the median for numeric columns only
df.fillna(df.select_dtypes(include='number').median(), inplace=True)

for column in df.select_dtypes(include='number').columns:
    df[column].fillna(df[column].median(), inplace=True)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [15]:
# Load dataset dari file CSV
df = pd.read_csv('iris.csv')

# Melihat beberapa baris pertama data
print(df.head())

# Extract features and labels
X = df.drop('species', axis=1).values
y = df['species'].values

# Encode label (string to integer)
le = LabelEncoder()
y = le.fit_transform(y)

# Split data menjadi train dan test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [16]:
# Membuat model KNN
knn = KNeighborsClassifier(n_neighbors=5)

# Melatih model
knn.fit(X_train, y_train)

# Memprediksi hasil pada data uji
y_pred = knn.predict(X_test)


In [17]:
# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy}')

# Menampilkan laporan klasifikasi
print(classification_report(y_test, y_pred))

# Menampilkan matriks
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)


Akurasi: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
